apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerter-app
spec:
  selector:
    matchLabels:
      run: alerter-app
  replicas: 1
  template:
    metadata:
      labels:
        run: alerter-app
    spec:
      containers:
        - name: alerter-app
          image: eu.gcr.io/stocker-300519/alerter:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "300Mi"
          env:
            - name: ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb+srv://stocker:halamish123@cluster2.3nsz4.mongodb.net/stocker"
            - name: TELEGRAM_TOKEN
              value: "1177225094:AAGtBg9BzIJVVXHelSSYnaQB6HBhyG1obiQ"
            - name: REDIS_IP
              value: "10.80.176.3"