apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: service-scale-up-job
spec:
  schedule: "0 13 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: service-scheduled-job
              image: eu.gcr.io/stocker-300519/service-scheduled-job:latest
              args:
#                - "kubectl patch hpa service-hpa --patch '{\"spec\":{\"minReplicas\":15}}'"
                - "kubectl patch deployment collector-scheduler-app --patch '{\"spec\":{\"replicas\":100}}'"

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: service-scale-down-job
spec:
  schedule: "30 20 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: service-scheduled-job
              image: eu.gcr.io/stocker-300519/service-scheduled-job:latest
              args:
                - "kubectl patch deployment collector-scheduler-app --patch '{\"spec\":{\"replicas\":0}}'"