#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: service-scale-up-job
#spec:
#  schedule: "0 13 * * 1-5"
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          restartPolicy: OnFailure
#          containers:
#            - name: service-scheduled-job
#              image: eu.gcr.io/stocker-300519/service-scheduled-job:latest
#              args:
#                #                - "kubectl patch hpa service-hpa --patch '{\"spec\":{\"minReplicas\":15}}'"
#                - "kubectl patch deployment collector-scheduler-app --patch '{\"spec\":{\"replicas\":100}}'"
#
#---
#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: service-scale-down-job
#spec:
#  schedule: "30 20 * * 1-5"
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          restartPolicy: OnFailure
#          containers:
#            - name: service-scheduled-job
#              image: eu.gcr.io/stocker-300519/service-scheduled-job:latest
#              args:
#                - "kubectl patch deployment collector-scheduler-app --patch '{\"spec\":{\"replicas\":0}}'"

#---
#{
#  "apiVersion": "v1",
#  "kind": "Namespace",
#  "metadata": {
#    "name": "scaling",
#    "labels": {
#      "name": "scaling"
#    }
#  }
#}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaler
rules:
#  - apiGroups: ["extensions","apps"]
#    resources: ["deployments", "replicasets"]
#    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - deployments/scale
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scaler
subjects:
  - kind: ServiceAccount
    name: scaler
    namespace: default

#---
#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: collector-starter
#  namespace: scaling
#spec:
#  schedule: "0 13 * * 1-5"
#  startingDeadlineSeconds: 10
#  concurrencyPolicy: Forbid
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          serviceAccountName: scaler
#          containers:
#            - name: scaler
#              image: eu.gcr.io/stocker-300519/scaler:1.0
#              command: ["/scaler"]
#              args: ["--namespace","default", "--label", "app=collector-app", "--action" , "start"]
#          restartPolicy: OnFailure
#
#---
#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: collector-stopper
#  namespace: scaling
#spec:
#  schedule: "30 20 * * 1-5"
#  startingDeadlineSeconds: 10
#  concurrencyPolicy: Forbid
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          serviceAccountName: scaler
#          containers:
#            - name: scaler
#              image: eu.gcr.io/stocker-300519/scaler:1.0
#              command: ["/scaler"]
#              args: ["--namespace","default", "--label", "app=collector-app", "--action" , "stop"]
#          restartPolicy: OnFailure
#
